In [1]:
import numpy as np
import pandas as pd

/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.4.3 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)


In [5]:
DATA_PATH="Data/"

In [11]:
data_file="1100_trust_w1.csv"
#pd.read_csv(DATA_PATH+data_file)
trust      =pd.read_csv(DATA_PATH+data_file,index_col=0)
trust=trust.fillna(0)
trust.as_matrix()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
         1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,
         1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,
         1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,

In [35]:
friendshipMAT2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
         1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,

In [33]:
friendshipMAT1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -2., -0.,  0.,  0.,  0.,  0.,  0.,
         0., -0.,  0.,  0., -2.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0., -0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,

In [52]:
import numpy as np
import csv
import os
# Data directory
#directory = "Controversies-Game-Theory-Project/Data"


# NA values are currently ignored

# Initilize the lists for correlations for time 1
corrEnemy1 = []
corrDislike1 = []
corrNeutral1 = []
corrLike1 = []
corrFriend1 = []

corrEnemy2 = []
corrDislike2 = []
corrNeutral2 = []
corrLike2 = []
corrFriend2 = []

# Loop over the files in the data folder
for filename in os.listdir(DATA_PATH):
    if filename.endswith("trust_w1.csv") and (filename!="1200_trust_w1.csv"):
        # Create trust vector
        trustfile = open(DATA_PATH+filename)
        reader = csv.reader(trustfile)


        trustDF      =pd.read_csv(DATA_PATH+filename,index_col=0)
        trustDF=trustDF.fillna(0)
        trustMAT=trustDF.as_matrix()        

        # Create the friendship vectors
        friendshipfile =(DATA_PATH+filename.split("_")[0]+"_affective_w1.csv")
        #reader = csv.reader(friendshipfile)

        friendshipDF      =pd.read_csv(friendshipfile,index_col=0)
        friendshipDF=friendshipDF.fillna(0)

        friendshipMAT=friendshipDF.as_matrix()

        friendshipMAT_2=(friendshipMAT== (-2))*np.ones_like(friendshipMAT)
        friendshipMAT_1=(friendshipMAT== (-1))*np.ones_like(friendshipMAT)
        friendshipMAT0=(friendshipMAT== (0))*np.ones_like(friendshipMAT)
        friendshipMAT1=(friendshipMAT== (1))*np.ones_like(friendshipMAT)
        friendshipMAT2=(friendshipMAT== (2))*np.ones_like(friendshipMAT)


        friendshipMAT1.flatten("F")
        corrEnemy1.append(np.corrcoef(trustMAT.flatten("F").astype(int), friendshipMAT_2.flatten("F").astype(int))[0])
        corrDislike1.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT_1.flatten("F"))[0])
        corrNeutral1.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT0.flatten("F"))[0])
        corrLike1.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT1.flatten("F"))[0])
        corrFriend1.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT2.flatten("F"))[0])

        #or filename.endswith("trust_w2.csv")
    elif filename.endswith("trust_w2.csv") and (filename!="1200_trust_w1.csv"):
        # Create trust vector
        trustfile = open(DATA_PATH+filename)
        reader = csv.reader(trustfile)


        trustDF      =pd.read_csv(DATA_PATH+filename,index_col=0)
        trustDF=trustDF.fillna(0)
        trustMAT=trustDF.as_matrix()        

        # Create the friendship vectors
        friendshipfile =(DATA_PATH+filename.split("_")[0]+"_affective_w2.csv")
        #reader = csv.reader(friendshipfile)

        friendshipDF      =pd.read_csv(friendshipfile,index_col=0)
        friendshipDF=friendshipDF.fillna(0)

        friendshipMAT=friendshipDF.as_matrix()

        friendshipMAT_2=(friendshipMAT== (-2))*np.ones_like(friendshipMAT)
        friendshipMAT_1=(friendshipMAT== (-1))*np.ones_like(friendshipMAT)
        friendshipMAT0=(friendshipMAT== (0))*np.ones_like(friendshipMAT)
        friendshipMAT1=(friendshipMAT== (1))*np.ones_like(friendshipMAT)
        friendshipMAT2=(friendshipMAT== (2))*np.ones_like(friendshipMAT)


        friendshipMAT1.flatten("F")

        corrEnemy2.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT_2.flatten("F"))[0])
        corrDislike2.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT_1.flatten("F"))[0])
        corrNeutral2.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT0.flatten("F"))[0])
        corrLike2.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT1.flatten("F"))[0])
        corrFriend2.append(np.corrcoef(trustMAT.flatten("F"), friendshipMAT2.flatten("F"))[0])

        
    else:
        continue

print("Correlations at time t1:")
print("Correlation with enemy: ", np.mean(np.array(corrEnemy1)))
print("Correlation with dislike: ", np.mean(np.array(corrDislike1)))
print("Correlation with neutral: ", np.mean(np.array(corrNeutral1)))
print("Correlation with like: ", np.mean(np.array(corrLike1)))
print("Correlation with friend: ", np.mean(np.array(corrFriend1)))

print("Correlations at time t2:")
print("Correlation with enemy: ", np.mean(np.array(corrEnemy2)))
print("Correlation with dislike: ", np.mean(np.array(corrDislike2)))
print("Correlation with neutral: ", np.mean(np.array(corrNeutral2)))
print("Correlation with like: ", np.mean(np.array(corrLike2)))
print("Correlation with friend: ", np.mean(np.array(corrFriend2)))


Correlations at time t1:
('Correlation with enemy: ', 0.48497994291727692)
('Correlation with dislike: ', 0.46955306588520185)
('Correlation with neutral: ', 0.3910986826595419)
('Correlation with like: ', 0.44490554450963266)
('Correlation with friend: ', 0.72057346948859025)
Correlations at time t2:
('Correlation with enemy: ', 0.48151434356932832)
('Correlation with dislike: ', 0.46656926464840803)
('Correlation with neutral: ', 0.38347883611822897)
('Correlation with like: ', 0.44607582524995182)
('Correlation with friend: ', 0.74404606827458575)
